const $=id=>document.getElementById(id),KEY="lifeResetV2",todayKey=new Date().toISOString().slice(0,10);
const defaults=()=>({date:todayKey,tasks:[{id:1,text:"Study or learn for 25 minutes",done:false},{id:2,text:"Move your body for a little while",done:false},{id:3,text:"Plan tomorrow before sleeping",done:false}],habits:{water:false,move:false,learn:false,plan:false},focusSeconds:0,streak:0,lastComplete:""});
function load(){try{let s=JSON.parse(localStorage.getItem(KEY));return !s||s.date!==todayKey?defaults():{...defaults(),...s,habits:{...defaults().habits,...s.habits}}}catch{return defaults()}}
let state=load(),duration=1500,left=1500,interval=null,running=false;
function save(){try{localStorage.setItem(KEY,JSON.stringify(state));$("saveStatus").textContent="Saved just now"}catch{}}
function toast(s){let t=$("toast");t.textContent=s;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),2100)}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){let list=$("taskList");list.innerHTML="";state.tasks.forEach(t=>{let row=document.createElement("div");row.className="task"+(t.done?" done":"");row.innerHTML=`<button class="check" aria-label="Toggle task">✓</button><span class="txt">${esc(t.text)}</span><button class="del" aria-label="Delete task">×</button>`;row.querySelector(".check").onclick=()=>{t.done=!t.done;update()};row.querySelector(".del").onclick=()=>{state.tasks=state.tasks.filter(x=>x.id!==t.id);update();toast("Task removed")};list.appendChild(row)});$("empty").hidden=state.tasks.length>0;let d=state.tasks.filter(t=>t.done).length,p=state.tasks.length?Math.round(d/state.tasks.length*100):0;$("done").textContent=d;$("total").textContent="/ "+state.tasks.length;$("percent").textContent=p;$("bar").style.width=p+"%";$("minutes").textContent=Math.floor(state.focusSeconds/60);$("streak").textContent=state.streak||0;$("left").textContent=(state.tasks.length-d)+" task"+(state.tasks.length-d===1?"":"s")+" left";$("taskTag").textContent=state.tasks.length+" tasks";document.querySelectorAll("[data-habit]").forEach(c=>c.checked=!!state.habits[c.dataset.habit]);save()}
function update(){render()}
function fmt(n){return String(Math.floor(n/60)).padStart(2,"0")+":"+String(n%60).padStart(2,"0")}
function timerUI(){ $("clock").textContent=fmt(left);let deg=(duration-left)/duration*360;$("timerRing").style.background=`conic-gradient(var(--accent) ${deg}deg,#303652 ${deg}deg)`;$("timerStatus").textContent=running?"FOCUS IN PROGRESS":left===0?"SESSION COMPLETE":"READY WHEN YOU ARE";$("start").textContent=running?"Ⅱ Pause focus":left===0?"↻ Start again":"▶ Start focus";document.title=fmt(left)+" — Life Reset"}
function stop(){clearInterval(interval);interval=null;running=false}
function tick(){if(left>0){left--;state.focusSeconds++;timerUI();if(left%5===0)save()}if(left===0){stop();timerUI();render();toast("Focus session complete — nice work!")}}
$("start").onclick=()=>{if(running){stop();timerUI();return}if(left===0)left=duration;running=true;timerUI();interval=setInterval(tick,1000)};
$("resetTimer").onclick=()=>{stop();left=duration;timerUI();toast("Timer reset")};
document.querySelectorAll("[data-min]").forEach(b=>b.onclick=()=>{stop();duration=Number(b.dataset.min)*60;left=duration;document.querySelectorAll("[data-min]").forEach(x=>x.classList.toggle("selected",x===b));timerUI()});
$("taskForm").onsubmit=e=>{e.preventDefault();let input=$("taskInput"),text=input.value.trim();if(!text){input.focus();return}state.tasks.push({id:Date.now(),text,done:false});input.value="";update();toast("Goal added")};
$("clearDone").onclick=()=>{let n=state.tasks.length;state.tasks=state.tasks.filter(t=>!t.done);update();toast(n===state.tasks.length?"No completed tasks yet":"Completed tasks cleared")};
document.querySelectorAll("[data-habit]").forEach(c=>c.onchange=()=>{state.habits[c.dataset.habit]=c.checked;if(Object.values(state.habits).every(Boolean)&&state.lastComplete!==todayKey){state.streak++;state.lastComplete=todayKey;toast("All daily habits complete!")}update()});
$("resetDay").onclick=()=>{if(confirm("Reset task and habit checkmarks? Focus time will stay.")){state.tasks.forEach(t=>t.done=false);Object.keys(state.habits).forEach(k=>state.habits[k]=false);update();toast("Today's checks reset")}};
$("theme").onclick=()=>{document.body.classList.toggle("mint");toast("Accent colour changed")};
$("today").textContent=new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});render();timerUI();