const $=id=>document.getElementById(id),KEY="lifeResetV3",HISTORY="lifeResetHistoryV3";
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
const todayKey=localDate(),defaults=()=>({date:todayKey,tasks:[{id:1,text:"Study or learn for 25 minutes",done:false},{id:2,text:"Move your body for a little while",done:false},{id:3,text:"Plan tomorrow before sleeping",done:false}],habits:{water:false,move:false,learn:false,plan:false},focusSeconds:0,streak:0});
function load(){try{let s=JSON.parse(localStorage.getItem(KEY));return !s||s.date!==todayKey?defaults():{...defaults(),...s,habits:{...defaults().habits,...s.habits}}}catch{return defaults()}}
function readHistory(){try{return JSON.parse(localStorage.getItem(HISTORY))||{}}catch{return {}}}
let state=load(),history=readHistory(),duration=1500,left=1500,interval=null,running=false,filter="all";
function save(){try{state.date=todayKey;localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(HISTORY,JSON.stringify(history));$("saveStatus").textContent="Saved on this browser ✓"}catch{$("saveStatus").textContent="Browser storage unavailable"}}
function toast(s){let t=$("toast");t.textContent=s;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),2100)}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function computeStreak(){let n=0,d=new Date();if(!history[todayKey])d.setDate(d.getDate()-1);for(let i=0;i<366;i++){let k=localDate(d);if(!history[k])break;n++;d.setDate(d.getDate()-1)}return n}
function render(){let list=$("taskList");list.innerHTML="";let shown=state.tasks.filter(t=>filter==="all"||(filter==="active"&&!t.done)||(filter==="done"&&t.done));shown.forEach(t=>{let row=document.createElement("div");row.className="task"+(t.done?" done":"");row.innerHTML=`<button class="check" aria-label="Toggle task completion">✓</button><span class="txt">${esc(t.text)}</span><button class="del" aria-label="Delete task">×</button>`;row.querySelector(".check").onclick=()=>{t.done=!t.done;update();toast(t.done?"Task completed — nice work!":"Task marked active")};row.querySelector(".del").onclick=()=>{state.tasks=state.tasks.filter(x=>x.id!==t.id);update();toast("Task removed")};list.appendChild(row)});$("empty").hidden=shown.length>0;$("empty").textContent=state.tasks.length===0?"No tasks yet. Add one small goal to begin.":"No tasks in this filter.";let d=state.tasks.filter(t=>t.done).length,p=state.tasks.length?Math.round(d/state.tasks.length*100):0;$("done").textContent=d;$("total").textContent="/ "+state.tasks.length;$("percent").textContent=p;$("bar").style.width=p+"%";$("minutes").textContent=Math.floor(state.focusSeconds/60);$("streak").textContent=computeStreak();$("left").textContent=(state.tasks.length-d)+" task"+(state.tasks.length-d===1?"":"s")+" left";$("taskTag").textContent=state.tasks.length+" tasks";document.querySelectorAll("[data-habit]").forEach(c=>c.checked=!!state.habits[c.dataset.habit]);let hc=Object.values(state.habits).filter(Boolean).length;$("habitCount").textContent=hc+" of 4 habits complete";$("habitBar").style.width=(hc/4*100)+"%";save()}
function update(){let hc=Object.values(state.habits).filter(Boolean).length;if(hc===4)history[todayKey]=true;else if(history[todayKey])delete history[todayKey];render()}
function fmt(n){return String(Math.floor(n/60)).padStart(2,"0")+":"+String(n%60).padStart(2,"0")}
function timerUI(){$("clock").textContent=fmt(left);let deg=(duration-left)/duration*360;$("timerRing").style.background=`conic-gradient(var(--accent) ${deg}deg,#303652 ${deg}deg)`;$("timerStatus").textContent=running?"FOCUS IN PROGRESS":left===0?"SESSION COMPLETE":"READY WHEN YOU ARE";$("start").textContent=running?"Ⅱ Pause focus":left===0?"↻ Start again":"▶ Start focus";document.title=fmt(left)+" — Life Reset"}
function stop(){clearInterval(interval);interval=null;running=false}
function tick(){if(left>0){left--;state.focusSeconds++;timerUI();if(left%5===0)save()}if(left===0){stop();timerUI();render();toast("Focus session complete — nice work!")}}
$("start").onclick=()=>{if(running){stop();timerUI();save();return}if(left===0)left=duration;running=true;timerUI();interval=setInterval(tick,1000)};
$("resetTimer").onclick=()=>{stop();left=duration;timerUI();toast("Timer reset")};
document.querySelectorAll("[data-min]").forEach(b=>b.onclick=()=>{stop();duration=Number(b.dataset.min)*60;left=duration;document.querySelectorAll("[data-min]").forEach(x=>x.classList.toggle("selected",x===b));timerUI()});
document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));render()});
$("taskForm").onsubmit=e=>{e.preventDefault();let input=$("taskInput"),text=input.value.trim();if(!text){input.focus();return}state.tasks.push({id:Date.now(),text,done:false});input.value="";filter="all";document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x.dataset.filter==="all"));update();toast("Goal added")};
$("clearDone").onclick=()=>{let n=state.tasks.length;state.tasks=state.tasks.filter(t=>!t.done);update();toast(n===state.tasks.length?"No completed tasks yet":"Completed tasks cleared")};
document.querySelectorAll("[data-habit]").forEach(c=>c.onchange=()=>{state.habits[c.dataset.habit]=c.checked;update();if(Object.values(state.habits).every(Boolean))toast("All daily habits complete! Great consistency.")});
$("resetDay").onclick=()=>{if(confirm("Reset task and habit checkmarks? Focus time will stay.")){state.tasks.forEach(t=>t.done=false);Object.keys(state.habits).forEach(k=>state.habits[k]=false);delete history[todayKey];update();toast("Today's checks reset")}};
$("theme").onclick=()=>{document.body.classList.toggle("mint");try{localStorage.setItem("lifeResetMint",document.body.classList.contains("mint")?"1":"0")}catch{}toast("Accent colour changed")};
try{if(localStorage.getItem("lifeResetMint")==="1")document.body.classList.add("mint")}catch{}
$("today").textContent=new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});render();timerUI();