const $=id=>document.getElementById(id),KEY="lifeResetV3",HISTORY="lifeResetHistoryV3";
function localDate(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
const todayKey=localDate(),defaults=()=>({date:todayKey,tasks:[{id:1,text:"Study or learn for 25 minutes",done:false},{id:2,text:"Move your body for a little while",done:false},{id:3,text:"Plan tomorrow before sleeping",done:false}],habits:{water:false,move:false,learn:false,plan:false},focusSeconds:0,streak:0});
function load(){try{let s=JSON.parse(localStorage.getItem(KEY));if(!s)return defaults();if(s.date!==todayKey){let oldHistory=JSON.parse(localStorage.getItem(HISTORY))||{};oldHistory[s.date]={...(oldHistory[s.date]||{}),tasksDone:(s.tasks||[]).filter(t=>t.done).length,tasksTotal:(s.tasks||[]).length,habitsDone:Object.values(s.habits||{}).filter(Boolean).length,focusMinutes:Math.floor((s.focusSeconds||0)/60),completeHabits:Object.values(s.habits||{}).filter(Boolean).length===Object.keys(s.habits||{}).length};localStorage.setItem(HISTORY,JSON.stringify(oldHistory));return defaults()}return {...defaults(),...s,habits:{...defaults().habits,...s.habits}}}catch{return defaults()}}
function readHistory(){try{return JSON.parse(localStorage.getItem(HISTORY))||{}}catch{return {}}}
let state=load(),history=readHistory(),duration=1500,left=1500,interval=null,running=false,filter="all",prioritySort=false,taskQuery="",profile={name:"",focusGoal:25};
try{profile={...profile,...JSON.parse(localStorage.getItem("lifeResetProfile")||"{}")} }catch{}
function save(){try{state.date=todayKey;history[todayKey]={...(history[todayKey]||{}),tasksDone:state.tasks.filter(t=>t.done).length,tasksTotal:state.tasks.length,habitsDone:Object.values(state.habits).filter(Boolean).length,focusMinutes:Math.floor(state.focusSeconds/60),completeHabits:Object.values(state.habits).every(Boolean)};localStorage.setItem(KEY,JSON.stringify(state));localStorage.setItem(HISTORY,JSON.stringify(history));$("saveStatus").textContent="Progress saved on this browser ✓"}catch{$("saveStatus").textContent="Browser storage unavailable"}}
function toast(s){let t=$("toast");t.textContent=s;t.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove("show"),2100)}
function esc(s){return s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function computeStreak(){let n=0,d=new Date();const qualifies=k=>{const h=history[k];return !!(h&&(h.completeHabits||h.habitsDone>=4))};if(!qualifies(todayKey))d.setDate(d.getDate()-1);for(let i=0;i<366;i++){if(!qualifies(localDate(d)))break;n++;d.setDate(d.getDate()-1)}return n}
function renderInsights(){const chart=$("weekChart"),cal=$("streakCalendar");if(!chart||!cal)return;chart.innerHTML="";cal.innerHTML="";let days=[],base=new Date();base.setDate(base.getDate()-6);let total=0,best={label:"",pct:-1};for(let i=0;i<7;i++){let d=new Date(base);d.setDate(base.getDate()+i);let key=localDate(d),h=history[key]||{},isToday=key===todayKey;let tasksDone=isToday?state.tasks.filter(t=>t.done).length:(h.tasksDone||0),tasksTotal=isToday?state.tasks.length:(h.tasksTotal||0),habitsDone=isToday?Object.values(state.habits).filter(Boolean).length:(h.habitsDone||0),focus=isToday?Math.floor(state.focusSeconds/60):(h.focusMinutes||0);let taskPct=tasksTotal?tasksDone/tasksTotal:0,habitPct=habitsDone/4,focusPct=Math.min(focus/25,1),pct=Math.round((taskPct*0.45+habitPct*0.4+focusPct*0.15)*100);if(!tasksTotal&&!habitsDone&&!focus)pct=0;days.push({key,label:d.toLocaleDateString(undefined,{weekday:"short"}),day:d.getDate(),pct,habitsDone});total+=pct;if(pct>best.pct)best={label:d.toLocaleDateString(undefined,{weekday:"long"}),pct};let el=document.createElement("div");el.className="weekday";el.innerHTML=`<div class="bararea"><span class="barvalue">${pct}%</span><i class="weekbar" style="height:${Math.max(pct,3)}%"></i></div><small>${d.toLocaleDateString(undefined,{weekday:"short"})}</small>`;el.title=`${key}: ${pct}% progress · ${focus} focus min`;chart.appendChild(el)}$("weekSummary").textContent=Math.round(total/7)+"% average";$("weekBest").textContent=best.pct>0?"Best day: "+best.label+" ("+best.pct+"%)":"Your first win is waiting today.";days.forEach(x=>{let e=document.createElement("div");e.className="calday"+(x.key===todayKey?" is-today":"");e.innerHTML=`<span class="calbox ${x.habitsDone>=4?"all-done":x.habitsDone>0?"some-done":"not-done"}" title="${x.habitsDone} of 4 habits"></span><small>${x.label}</small><b>${x.day}</b>`;cal.appendChild(e)})}
function render(){let list=$("taskList");list.innerHTML="";let query=taskQuery.trim().toLowerCase();let shown=state.tasks.filter(t=>(filter==="all"||(filter==="active"&&!t.done)||(filter==="done"&&t.done))&&(!query||t.text.toLowerCase().includes(query)));if(prioritySort){const rank={high:0,normal:1,low:2};shown.sort((a,b)=>(a.done-b.done)||((rank[a.priority]??1)-(rank[b.priority]??1)))}shown.forEach(t=>{let row=document.createElement("div");row.className="task"+(t.done?" done":"")+" priority-"+(t.priority||"normal");row.innerHTML=`<button class="check" aria-label="Toggle task completion">✓</button><span class="txt">${esc(t.text)}</span><span class="priority-label">${({high:"HIGH",normal:"NORMAL",low:"LOW"})[t.priority||"normal"]}</span><button class="del" aria-label="Delete task">×</button>`;row.querySelector(".check").onclick=()=>{t.done=!t.done;update();toast(t.done?"Task completed — nice work!":"Task marked active")};row.querySelector(".del").onclick=()=>{state.tasks=state.tasks.filter(x=>x.id!==t.id);update();toast("Task removed")};list.appendChild(row)});$("countAll").textContent=state.tasks.length;$("countActive").textContent=state.tasks.filter(t=>!t.done).length;$("countDone").textContent=state.tasks.filter(t=>t.done).length;$("empty").hidden=shown.length>0;$("empty").textContent=state.tasks.length===0?"No tasks yet. Add one small goal to begin.":"No tasks in this filter.";let d=state.tasks.filter(t=>t.done).length,p=state.tasks.length?Math.round(d/state.tasks.length*100):0;$("done").textContent=d;$("total").textContent="/ "+state.tasks.length;$("percent").textContent=p;$("bar").style.width=p+"%";$("minutes").textContent=Math.floor(state.focusSeconds/60);let focusMins=Math.floor(state.focusSeconds/60),goal=Math.max(1,Number(profile.focusGoal)||25);$("focusGoalLabel").textContent=focusMins+" / "+goal+" min";$("focusGoalBar").style.width=Math.min(100,focusMins/goal*100)+"%";$("streak").textContent=computeStreak();$("left").textContent=(state.tasks.length-d)+" task"+(state.tasks.length-d===1?"":"s")+" left";$("taskTag").textContent=state.tasks.length+" tasks";document.querySelectorAll("[data-habit]").forEach(c=>c.checked=!!state.habits[c.dataset.habit]);let hc=Object.values(state.habits).filter(Boolean).length;$("habitCount").textContent=hc+" of 4 habits complete";$("habitBar").style.width=(hc/4*100)+"%";save();renderInsights()}
function update(){render()}
function fmt(n){return String(Math.floor(n/60)).padStart(2,"0")+":"+String(n%60).padStart(2,"0")}
function timerUI(){$("clock").textContent=fmt(left);let deg=(duration-left)/duration*360;$("timerRing").style.background=`conic-gradient(var(--accent) ${deg}deg,#303652 ${deg}deg)`;$("timerStatus").textContent=running?"FOCUS IN PROGRESS":left===0?"SESSION COMPLETE":"READY WHEN YOU ARE";$("start").textContent=running?"Ⅱ Pause focus":left===0?"↻ Start again":"▶ Start focus";document.title=fmt(left)+" — Life Reset"}
function stop(){clearInterval(interval);interval=null;running=false}
function tick(){if(left>0){left--;state.focusSeconds++;timerUI();if(left%5===0)save()}if(left===0){stop();timerUI();render();toast("Focus session complete — nice work!")}}
function applyProfile(){const name=(profile.name||"").trim();$("welcomeLine").textContent=name?`WELCOME BACK, ${name.toLocaleUpperCase()} · YOUR NEXT CHAPTER STARTS HERE`:"YOUR NEXT CHAPTER STARTS HERE";$("profileName").value=profile.name||"";$("focusGoal").value=String(profile.focusGoal||25);$("heroSubtitle").textContent=name?`Your space, your pace, ${name}. Small steps still count.`:"Small steps. Real progress. One day at a time."}
$("profileForm").onsubmit=e=>{e.preventDefault();profile.name=$("profileName").value.trim();profile.focusGoal=Number($("focusGoal").value)||25;try{localStorage.setItem("lifeResetProfile",JSON.stringify(profile))}catch{}applyProfile();render();toast("Your personal setup is saved ✓")};
$("start").onclick=()=>{if(running){stop();timerUI();save();return}if(left===0)left=duration;running=true;timerUI();interval=setInterval(tick,1000)};
$("resetTimer").onclick=()=>{stop();left=duration;timerUI();toast("Timer reset")};
document.querySelectorAll("[data-min]").forEach(b=>b.onclick=()=>{stop();duration=Number(b.dataset.min)*60;left=duration;document.querySelectorAll("[data-min]").forEach(x=>x.classList.toggle("selected",x===b));timerUI()});
document.querySelectorAll("[data-filter]").forEach(b=>b.onclick=()=>{filter=b.dataset.filter;document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x===b));render()});
$("taskSearch").addEventListener("input",e=>{taskQuery=e.target.value;render()});$("sortTasks").onclick=()=>{prioritySort=!prioritySort;$("sortTasks").textContent=prioritySort?"↕ Default order":"↕ Priority first";render();toast(prioritySort?"High-priority tasks shown first":"Original task order restored")};
$("taskForm").onsubmit=e=>{e.preventDefault();let input=$("taskInput"),text=input.value.trim();if(!text){input.focus();return}state.tasks.push({id:Date.now(),text,done:false,priority:$("taskPriority").value});input.value="";$("taskPriority").value="normal";filter="all";document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x.dataset.filter==="all"));update();toast("Goal added")};
$("clearDone").onclick=()=>{let n=state.tasks.length;state.tasks=state.tasks.filter(t=>!t.done);update();toast(n===state.tasks.length?"No completed tasks yet":"Completed tasks cleared")};
document.querySelectorAll("[data-habit]").forEach(c=>c.onchange=()=>{state.habits[c.dataset.habit]=c.checked;update();if(Object.values(state.habits).every(Boolean))toast("All daily habits complete! Great consistency.")});
$("resetDay").onclick=()=>{if(confirm("Reset task and habit checkmarks? Focus time will stay.")){state.tasks.forEach(t=>t.done=false);Object.keys(state.habits).forEach(k=>state.habits[k]=false);delete history[todayKey];update();toast("Today's checks reset")}};
$("theme").onclick=()=>{document.body.classList.toggle("mint");try{localStorage.setItem("lifeResetMint",document.body.classList.contains("mint")?"1":"0")}catch{}toast("Accent colour changed")};
try{if(localStorage.getItem("lifeResetMint")==="1")document.body.classList.add("mint")}catch{}
$("today").textContent=new Date().toLocaleDateString(undefined,{weekday:"long",month:"long",day:"numeric"});applyProfile();render();renderInsights();timerUI();
window.addEventListener("beforeunload",save);document.addEventListener("visibilitychange",()=>{if(document.hidden)save()});
